import type { HospitalState, OrganizationRecord, UserRecord } from "../domain/types.js";

export const DEMO_ACCOUNT_PASSWORD = "Medi2026!Care";
export const DEMO_REFERENCE_DATE = "2026-08-09";
export const DEMO_ORGANIZATION: OrganizationRecord = {
  id: "org-medivanta-general",
  name: "MediVanta General Hospital",
  slug: "medivanta-general",
  address: "221 Care Avenue",
  city: "Chennai",
  state: "Tamil Nadu",
  contactPhone: "+91 44 4000 2200",
  contactEmail: "hello@medivanta.demo",
  emergencyContact: "+91 44 4000 2299",
  operatingHours: "24/7 emergency · Outpatient 08:00 - 20:00",
  timezone: "Asia/Calcutta",
  defaultLanguage: "English",
  emergencyServicesEnabled: true,
  defaultConsultationSlotDurationMinutes: 30,
};

const demoBookingCapacity = {
  doctorSlotCapacity: 1,
  defaultMaxAppointmentsPerSession: 6,
  labSlotCapacity: 5,
  sessions: [
    {
      id: "morning",
      label: "Morning",
      startTime: "08:00",
      endTime: "11:59",
      maxAppointments: 6,
    },
    {
      id: "afternoon",
      label: "Afternoon",
      startTime: "12:00",
      endTime: "15:59",
      maxAppointments: 6,
    },
    {
      id: "evening",
      label: "Evening",
      startTime: "16:00",
      endTime: "18:30",
      maxAppointments: 4,
    },
  ],
} as const;

const demoLabTests = [
  {
    id: "lab-cbc",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Complete Blood Count (CBC)",
    priceCents: 120000,
  },
  {
    id: "lab-glucose",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Blood Glucose",
    priceCents: 45000,
  },
  {
    id: "lab-lipid",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Lipid Profile",
    priceCents: 180000,
  },
  {
    id: "lab-thyroid",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Thyroid Profile",
    priceCents: 165000,
  },
  {
    id: "lab-liver",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Liver Function Test",
    priceCents: 210000,
  },
  {
    id: "lab-kidney",
    organizationId: DEMO_ORGANIZATION.id,
    name: "Kidney Function Test",
    priceCents: 195000,
  },
] as const;

export function createDemoHospitalState(): HospitalState {
  const demoMedicineCatalog = [
    {
      id: "medcat-paracetamol-500-tablet",
      organizationId: DEMO_ORGANIZATION.id,
      name: "Paracetamol",
      strength: "500 mg",
      unit: "tablet",
      genericName: "Paracetamol",
      active: true,
      createdAt: "2026-08-01T08:00:00.000Z",
      updatedAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "medcat-ors-sachet",
      organizationId: DEMO_ORGANIZATION.id,
      name: "Oral rehydration salts",
      strength: "ORS",
      unit: "sachet",
      genericName: "ORS",
      active: true,
      createdAt: "2026-08-01T08:00:00.000Z",
      updatedAt: "2026-08-01T08:00:00.000Z",
    },
    {
      id: "medcat-vitd3-60000-capsule",
      organizationId: DEMO_ORGANIZATION.id,
      name: "Vitamin D3",
      strength: "60,000 IU",
      unit: "capsule",
      genericName: "Cholecalciferol",
      active: true,
      createdAt: "2026-08-01T08:00:00.000Z",
      updatedAt: "2026-08-01T08:00:00.000Z",
    },
  ] as const;

  return {
    organization: DEMO_ORGANIZATION,
    departments: [
      {
        id: "dept-general-medicine",
        organizationId: DEMO_ORGANIZATION.id,
        code: "GM",
        name: "General Medicine",
        description: "Adult consultations, follow-up care, and chronic care planning.",
        status: "Operational",
        location: "North Wing, Level 2",
      },
      {
        id: "dept-cardiology",
        organizationId: DEMO_ORGANIZATION.id,
        code: "CARD",
        name: "Cardiology",
        description: "Heart health consultations, diagnostics, and recovery planning.",
        status: "Busy",
        location: "Heart Centre, Level 3",
      },
      {
        id: "dept-pediatrics",
        organizationId: DEMO_ORGANIZATION.id,
        code: "PED",
        name: "Pediatrics",
        description: "Child wellness, family care, and pediatric follow-up visits.",
        status: "Operational",
        location: "Family Care Block, Level 1",
      },
      {
        id: "dept-orthopedics",
        organizationId: DEMO_ORGANIZATION.id,
        code: "ORTHO",
        name: "Orthopedics",
        description: "Musculoskeletal care, fracture review, and post-procedure follow-up.",
        status: "Operational",
        location: "Surgical Wing, Level 2",
      },
      {
        id: "dept-neurology",
        organizationId: DEMO_ORGANIZATION.id,
        code: "NEURO",
        name: "Neurology",
        description: "Neurology consultations, symptom review, and specialist assessment.",
        status: "Limited",
        location: "Specialty Clinic, Level 4",
      },
      {
        id: "dept-dermatology",
        organizationId: DEMO_ORGANIZATION.id,
        code: "DERM",
        name: "Dermatology",
        description: "Skin health consultations and follow-up care.",
        status: "Operational",
        location: "Outpatient Wing, Level 2",
      },
      {
        id: "dept-ent",
        organizationId: DEMO_ORGANIZATION.id,
        code: "ENT",
        name: "ENT",
        description: "Ear, nose, and throat specialist services.",
        status: "Operational",
        location: "Specialty Clinic, Level 3",
      },
      {
        id: "dept-ophthalmology",
        organizationId: DEMO_ORGANIZATION.id,
        code: "OPH",
        name: "Ophthalmology",
        description: "Eye examinations, specialist consultations, and follow-up visits.",
        status: "Operational",
        location: "Vision Centre, Level 2",
      },
      {
        id: "dept-radiology",
        organizationId: DEMO_ORGANIZATION.id,
        code: "RAD",
        name: "Radiology",
        description: "Imaging coordination, scanning workflow, and report preparation.",
        status: "Busy",
        location: "Diagnostics Block, Ground Floor",
      },
      {
        id: "dept-laboratory",
        organizationId: DEMO_ORGANIZATION.id,
        code: "LAB",
        name: "Laboratory",
        description: "Sample collection, test processing, and results support.",
        status: "Operational",
        location: "Diagnostics Block, Ground Floor",
      },
      {
        id: "dept-emergency",
        organizationId: DEMO_ORGANIZATION.id,
        code: "ER",
        name: "Emergency",
        description: "Urgent assessment, acute care intake, and emergency support.",
        status: "Emergency priority",
        location: "Emergency Entrance, Ground Floor",
      },
    ],
    doctors: [
      {
        id: "doc-anaya-sharma",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Anaya Sharma",
        specialization: "Internal Medicine",
        departmentId: "dept-general-medicine",
        status: "Consulting",
        availability: "Consulting today",
        shiftLabel: "08:00 - 14:00",
      },
      {
        id: "doc-rohan-mehta",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Rohan Mehta",
        specialization: "Emergency Medicine",
        departmentId: "dept-emergency",
        status: "Emergency duty",
        availability: "On emergency rotation",
        shiftLabel: "07:00 - 19:00",
      },
      {
        id: "doc-meera-iqbal",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Meera Iqbal",
        specialization: "Pediatrics",
        departmentId: "dept-pediatrics",
        status: "Available",
        availability: "Follow-up clinic open",
        shiftLabel: "10:00 - 18:00",
      },
      {
        id: "doc-vivek-menon",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Vivek Menon",
        specialization: "Cardiology",
        departmentId: "dept-cardiology",
        status: "Available",
        availability: "Next clinic session tomorrow",
        shiftLabel: "09:00 - 17:00",
      },
      {
        id: "doc-neha-sen",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Neha Sen",
        specialization: "Radiology",
        departmentId: "dept-radiology",
        status: "Consulting",
        availability: "Imaging sessions in progress",
        shiftLabel: "08:00 - 16:00",
      },
      {
        id: "doc-kiran-iyer",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Kiran Iyer",
        specialization: "Orthopedics",
        departmentId: "dept-orthopedics",
        status: "On break",
        availability: "Returns at 13:00",
        shiftLabel: "08:00 - 16:00",
      },
      {
        id: "doc-sana-reddy",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Sana Reddy",
        specialization: "Dermatology",
        departmentId: "dept-dermatology",
        status: "Off duty",
        availability: "Next clinic tomorrow",
        shiftLabel: "Off duty today",
      },
      {
        id: "doc-arjun-roy",
        organizationId: DEMO_ORGANIZATION.id,
        name: "Dr. Arjun Roy",
        specialization: "Neurology",
        departmentId: "dept-neurology",
        status: "Available",
        availability: "Review clinic active",
        shiftLabel: "11:00 - 19:00",
      },
    ],
    medicineCatalog: [...demoMedicineCatalog],
    appointments: [
      {
        id: "APT-2001",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Aarav Verma",
        doctorId: "doc-vivek-menon",
        departmentId: "dept-cardiology",
        appointmentDate: DEMO_REFERENCE_DATE,
        appointmentTime: "09:30",
        reasonForAppointment: "Stable hypertension follow-up",
        consultationMode: "In Person",
        status: "Checked in",
      },
      {
        id: "APT-2002",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Sana Khan",
        doctorId: "doc-neha-sen",
        departmentId: "dept-radiology",
        appointmentDate: DEMO_REFERENCE_DATE,
        appointmentTime: "10:00",
        reasonForAppointment: "Diagnostic imaging review",
        consultationMode: "In Person",
        status: "In consultation",
      },
      {
        id: "APT-2003",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Maya Joseph",
        doctorId: "doc-anaya-sharma",
        departmentId: "dept-general-medicine",
        appointmentDate: DEMO_REFERENCE_DATE,
        appointmentTime: "10:45",
        reasonForAppointment: "General fever follow-up",
        consultationMode: "In Person",
        status: "Completed",
      },
      {
        id: "APT-2004",
        organizationId: DEMO_ORGANIZATION.id,
        patientId: "user-patient",
        patientName: "Ritesh Nair",
        doctorId: "doc-meera-iqbal",
        departmentId: "dept-pediatrics",
        appointmentDate: DEMO_REFERENCE_DATE,
        appointmentTime: "11:15",
        reasonForAppointment: "Persistent fever",
        consultationMode: "Online",
        status: "Scheduled",
      },
      {
        id: "APT-2005",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Ishita Das",
        doctorId: "doc-kiran-iyer",
        departmentId: "dept-orthopedics",
        appointmentDate: DEMO_REFERENCE_DATE,
        appointmentTime: "12:10",
        reasonForAppointment: "Knee pain review",
        consultationMode: "In Person",
        status: "Scheduled",
      },
      {
        id: "APT-2006",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Kabir Patel",
        doctorId: "doc-arjun-roy",
        departmentId: "dept-neurology",
        appointmentDate: "2026-08-10",
        appointmentTime: "14:00",
        reasonForAppointment: "Headache and dizziness",
        consultationMode: "In Person",
        status: "Scheduled",
      },
    ],
    queueEntries: [
      {
        id: "Q-3101",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Aarav Verma",
        departmentId: "dept-cardiology",
        doctorId: "doc-vivek-menon",
        appointmentId: "APT-2001",
        status: "Waiting",
        createdAt: "09:18",
        updatedAt: "09:18",
      },
      {
        id: "Q-3102",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Sana Khan",
        departmentId: "dept-radiology",
        doctorId: "doc-neha-sen",
        appointmentId: "APT-2002",
        status: "In consultation",
        createdAt: "09:48",
        updatedAt: "10:06",
      },
      {
        id: "Q-3103",
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Maya Joseph",
        departmentId: "dept-general-medicine",
        doctorId: "doc-anaya-sharma",
        appointmentId: "APT-2003",
        status: "Completed",
        createdAt: "10:11",
        updatedAt: "10:42",
      },
    ],
    medicalRecords: [
      {
        id: "MR-1001",
        patientId: "user-patient",
        patientName: "Ritesh Nair",
        doctorId: "doc-meera-iqbal",
        doctorName: "Dr. Meera Iqbal",
        hospitalId: DEMO_ORGANIZATION.id,
        organizationId: DEMO_ORGANIZATION.id,
        visitDate: "2026-08-05",
        diagnosis: "Seasonal viral fever",
        clinicalNotes:
          "Low-grade fever with fatigue for three days. No respiratory distress observed during review.",
        treatmentAdvice:
          "Continue hydration, paracetamol as advised, and review again if fever persists beyond 48 hours.",
        createdAt: "2026-08-05T11:40:00.000Z",
      },
      {
        id: "MR-1002",
        patientId: "external:aarav-verma",
        patientName: "Aarav Verma",
        doctorId: "doc-vivek-menon",
        doctorName: "Dr. Vivek Menon",
        appointmentId: "APT-2001",
        hospitalId: DEMO_ORGANIZATION.id,
        organizationId: DEMO_ORGANIZATION.id,
        visitDate: DEMO_REFERENCE_DATE,
        diagnosis: "Stable hypertension follow-up",
        clinicalNotes:
          "Blood pressure remains controlled with current regimen. Continue low-sodium diet and exercise plan.",
        treatmentAdvice:
          "Maintain medication adherence and return for cardiology review in six weeks.",
        createdAt: `${DEMO_REFERENCE_DATE}T10:15:00.000Z`,
      },
    ],
    prescriptions: [
      {
        id: "RX-2001",
        patientId: "user-patient",
        patientName: "Ritesh Nair",
        doctorId: "doc-meera-iqbal",
        doctorName: "Dr. Meera Iqbal",
        hospitalId: DEMO_ORGANIZATION.id,
        organizationId: DEMO_ORGANIZATION.id,
        medicines: [
          {
            medicineId: "medcat-paracetamol-500-tablet",
            medicineName: "Paracetamol",
            strength: "500 mg",
            doseQuantity: 1,
            doseUnit: "tablet",
            dosage: "1 tablet",
            frequency: "Three times daily",
            durationValue: 3,
            durationUnit: "days",
            duration: "3 days",
            totalQuantity: 9,
          },
          {
            medicineId: "medcat-ors-sachet",
            medicineName: "Oral rehydration salts",
            strength: "ORS",
            doseQuantity: 1,
            doseUnit: "sachet",
            dosage: "1 sachet",
            frequency: "As needed",
            durationValue: 3,
            durationUnit: "days",
            duration: "3 days",
            totalQuantity: 3,
          },
        ],
        instructions: "Take after meals and return if fever persists or new symptoms appear.",
        status: "Issued",
        createdAt: "2026-08-05T11:45:00.000Z",
      },
      {
        id: "RX-2002",
        patientId: "external:maya-joseph",
        patientName: "Maya Joseph",
        doctorId: "doc-anaya-sharma",
        doctorName: "Dr. Anaya Sharma",
        appointmentId: "APT-2003",
        hospitalId: DEMO_ORGANIZATION.id,
        organizationId: DEMO_ORGANIZATION.id,
        medicines: [
          {
            medicineId: "medcat-vitd3-60000-capsule",
            medicineName: "Vitamin D3",
            strength: "60,000 IU",
            doseQuantity: 1,
            doseUnit: "capsule",
            dosage: "1 capsule",
            frequency: "Weekly",
            durationValue: 6,
            durationUnit: "weeks",
            duration: "6 weeks",
            totalQuantity: 6,
          },
        ],
        instructions: "Take with food once every week for six weeks.",
        status: "Dispensed",
        createdAt: `${DEMO_REFERENCE_DATE}T10:50:00.000Z`,
        dispensedAt: `${DEMO_REFERENCE_DATE}T12:20:00.000Z`,
        dispensedBy: {
          id: "user-pharmacist",
          name: "Rahul Sethi",
        },
      },
    ],
    labTests: [...demoLabTests],
    labRequests: [
      {
        id: "LABREQ-5001",
        patientId: "user-patient",
        hospitalId: DEMO_ORGANIZATION.id,
        organizationId: DEMO_ORGANIZATION.id,
        patientName: "Ritesh Nair",
        testId: "lab-cbc",
        testName: "Complete Blood Count (CBC)",
        departmentId: "dept-laboratory",
        requestedDate: "2026-08-11",
        requestedTime: "09:00",
        status: "Scheduled",
        createdAt: "2026-08-09T09:00:00.000Z",
      },
    ],
    labReports: [],
    invoices: [
      {
        id: "INV-2001",
        invoiceNumber: "MV-INV-2001",
        patientId: "user-patient",
        patientName: "Ritesh Nair",
        organizationId: DEMO_ORGANIZATION.id,
        hospitalId: DEMO_ORGANIZATION.id,
        sourceType: "lab-request",
        sourceId: "LABREQ-5001",
        createdAt: "2026-08-09T09:02:00.000Z",
        dueDate: "2026-08-16",
        subtotalCents: 120000,
        totalCents: 120000,
        amountPaidCents: 0,
        amountDueCents: 120000,
        paymentStatus: "Pending",
        items: [
          {
            id: "INVITEM-2001",
            invoiceId: "INV-2001",
            organizationId: DEMO_ORGANIZATION.id,
            description: "Complete Blood Count (CBC)",
            category: "Laboratory",
            quantity: 1,
            unitAmountCents: 120000,
            totalAmountCents: 120000,
            sourceType: "lab-request",
            sourceId: "LABREQ-5001",
          },
        ],
        payments: [],
      },
      {
        id: "INV-2002",
        invoiceNumber: "MV-INV-2002",
        patientId: "external:maya-joseph",
        patientName: "Maya Joseph",
        organizationId: DEMO_ORGANIZATION.id,
        hospitalId: DEMO_ORGANIZATION.id,
        sourceType: "prescription",
        sourceId: "RX-2002",
        createdAt: `${DEMO_REFERENCE_DATE}T12:20:00.000Z`,
        dueDate: DEMO_REFERENCE_DATE,
        subtotalCents: 35000,
        totalCents: 35000,
        amountPaidCents: 35000,
        amountDueCents: 0,
        paymentStatus: "Paid",
        items: [
          {
            id: "INVITEM-2002",
            invoiceId: "INV-2002",
            organizationId: DEMO_ORGANIZATION.id,
            description: "Vitamin D3 60,000 IU",
            category: "Medicine",
            quantity: 1,
            unitAmountCents: 35000,
            totalAmountCents: 35000,
            sourceType: "prescription",
            sourceId: "RX-2002",
          },
        ],
        payments: [
          {
            id: "PAY-2001",
            invoiceId: "INV-2002",
            patientId: "external:maya-joseph",
            organizationId: DEMO_ORGANIZATION.id,
            amountCents: 35000,
            method: "Cash",
            referenceNumber: "CASH-2001",
            paidAt: `${DEMO_REFERENCE_DATE}T12:25:00.000Z`,
            recordedBy: {
              id: "user-receptionist",
              name: "Anika Rao",
            },
          },
        ],
      },
    ],
    inventoryItems: [
      {
        id: "INVSTOCK-1001",
        organizationId: DEMO_ORGANIZATION.id,
        medicineId: "medcat-paracetamol-500-tablet",
        medicineName: "Paracetamol 500 mg",
        genericName: "Paracetamol",
        batchNumber: "PCM-2607-A",
        quantityInStock: 180,
        unit: "tablet",
        unitPriceCents: 600,
        expiryDate: "2027-02-28",
        reorderLevel: 40,
        manufacturer: "Medisphere Pharma",
        createdAt: "2026-07-01T08:00:00.000Z",
        updatedAt: "2026-08-09T08:00:00.000Z",
      },
      {
        id: "INVSTOCK-1002",
        organizationId: DEMO_ORGANIZATION.id,
        medicineId: "medcat-ors-sachet",
        medicineName: "Oral rehydration salts",
        genericName: "ORS",
        batchNumber: "ORS-2607-B",
        quantityInStock: 60,
        unit: "sachet",
        unitPriceCents: 2500,
        expiryDate: "2027-01-31",
        reorderLevel: 20,
        manufacturer: "Careline Nutrition",
        createdAt: "2026-07-05T08:00:00.000Z",
        updatedAt: "2026-08-09T08:00:00.000Z",
      },
      {
        id: "INVSTOCK-1003",
        organizationId: DEMO_ORGANIZATION.id,
        medicineId: "medcat-vitd3-60000-capsule",
        medicineName: "Vitamin D3 60,000 IU",
        genericName: "Cholecalciferol",
        batchNumber: "VITD-2606-C",
        quantityInStock: 8,
        unit: "capsule",
        unitPriceCents: 35000,
        expiryDate: "2026-10-31",
        reorderLevel: 10,
        manufacturer: "Sunwell Labs",
        createdAt: "2026-06-15T08:00:00.000Z",
        updatedAt: "2026-08-09T12:20:00.000Z",
      },
    ],
    notifications: [
      {
        id: "NOTIFY-1001",
        userId: "user-patient",
        organizationId: DEMO_ORGANIZATION.id,
        title: "Laboratory request scheduled",
        message: "Your Complete Blood Count (CBC) is scheduled for 11 Aug 2026 at 09:00.",
        category: "Laboratory",
        relatedEntityType: "lab-request",
        relatedEntityId: "LABREQ-5001",
        read: false,
        createdAt: "2026-08-09T09:05:00.000Z",
      },
      {
        id: "NOTIFY-1002",
        userId: "user-pharmacist",
        organizationId: DEMO_ORGANIZATION.id,
        title: "Low stock warning",
        message: "Vitamin D3 60,000 IU is approaching the reorder level.",
        category: "Inventory",
        relatedEntityType: "inventory-item",
        relatedEntityId: "INVSTOCK-1003",
        read: false,
        createdAt: "2026-08-09T12:30:00.000Z",
      },
    ],
    familyMembers: [],
    medicalHistoryEntries: [],
    clinicalAttachments: [],
    telemedicineSessions: [],
    bookingCapacity: { ...demoBookingCapacity, sessions: [...demoBookingCapacity.sessions] },
    configuredSupportLines: 9,
  };
}

export function createDemoUsers(passwordHash: string): UserRecord[] {
  return [
    {
      id: "user-patient",
      organizationId: DEMO_ORGANIZATION.id,
      email: "patient@medivanta.demo",
      displayName: "Ritesh Nair",
      role: "patient",
      passwordHash,
      patientName: "Ritesh Nair",
      phoneNumber: "9876543210",
      gender: "Male",
      dateOfBirth: "1994-03-18",
      bloodGroup: "B+",
      address: "22 Lake View Road, Chennai",
      addressLine1: "22 Lake View Road",
      city: "Chennai",
      state: "Tamil Nadu",
      postalCode: "600018",
      emergencyContactName: "Anita Nair",
      emergencyContactPhone: "9876501234",
      emergencyContact: "Anita Nair · 9876501234",
      allergies: "None reported",
      medicalConditions: "None reported",
      preferredLanguage: "English",
    },
    {
      id: "user-doctor",
      organizationId: DEMO_ORGANIZATION.id,
      email: "doctor@medivanta.demo",
      displayName: "Dr. Meera Iqbal",
      role: "doctor",
      passwordHash,
      doctorId: "doc-meera-iqbal",
      staffStatus: "Active",
      phoneNumber: "9876500001",
      gender: "Female",
      designation: "Consultant Pediatrician",
      qualifications: "MBBS, MD Pediatrics",
      experience: "9 years pediatric practice",
      shift: "Day Shift",
      professionalRegistrationNumber: "TNMC-45821",
      languages: "English, Hindi, Tamil",
      consultationFee: "INR 900",
      consultationMode: "In-person and Video",
      availableTimings: "10:00 - 18:00",
      profileVerificationStatus: "Verified",
    },
    {
      id: "user-receptionist",
      organizationId: DEMO_ORGANIZATION.id,
      email: "receptionist@medivanta.demo",
      displayName: "Anika Rao",
      role: "receptionist",
      staffStatus: "Active",
      passwordHash,
      phoneNumber: "9876500002",
      gender: "Female",
      designation: "Reception Executive",
      shift: "Morning Shift",
      deskLabel: "Front Desk A",
    },
    {
      id: "user-laboratory",
      organizationId: DEMO_ORGANIZATION.id,
      email: "lab@medivanta.demo",
      displayName: "Nisha Balan",
      role: "laboratory",
      departmentId: "dept-laboratory",
      staffStatus: "Active",
      passwordHash,
      phoneNumber: "9876500003",
      gender: "Female",
      designation: "Laboratory Technologist",
      qualifications: "B.Sc MLT, Sample Handling Certification",
      shift: "Day Shift",
    },
    {
      id: "user-pharmacist",
      organizationId: DEMO_ORGANIZATION.id,
      email: "pharmacist@medivanta.demo",
      displayName: "Rahul Sethi",
      role: "pharmacist",
      staffStatus: "Active",
      passwordHash,
      phoneNumber: "9876500004",
      gender: "Male",
      designation: "Clinical Pharmacist",
      qualifications: "B.Pharm",
      professionalRegistrationNumber: "TNPC-44721",
      shift: "Day Shift",
    },
    {
      id: "user-admin",
      organizationId: DEMO_ORGANIZATION.id,
      email: "admin@medivanta.demo",
      displayName: "Priya Deshmukh",
      role: "administrator",
      staffStatus: "Active",
      passwordHash,
      phoneNumber: "9876500005",
      gender: "Female",
      designation: "Hospital Administrator",
      administrativeUnit: "Administration",
    },
  ];
}
