import type { Capability, UserRole } from "../domain/types.js";

export const roleCapabilities: Record<UserRole, Capability[]> = {
  patient: [
    "appointment:create",
    "appointment:update",
    "appointment:cancel",
    "appointment:view",
    "search:view",
    "lab-request:create",
    "health-records:view",
    "prescriptions:view",
    "lab-reports:view",
    "billing:view",
    "notifications:view",
    "payment:record",
    "profile:view",
    "profile:update",
    "family-member:manage",
    "medical-history:create",
    "clinical-attachment:create",
    "telemedicine:join",
  ],
  doctor: [
    "appointment:view",
    "search:view",
    "queue:view",
    "doctor:view",
    "department:view",
    "schedule:view",
    "patients:view",
    "prescriptions:view",
    "prescription:create",
    "health-records:view",
    "health-records:create",
    "lab-request:create",
    "lab-reports:view",
    "notifications:view",
    "profile:view",
    "profile:update",
    "clinical-attachment:create",
    "telemedicine:join",
  ],
  laboratory: [
    "laboratory:view",
    "lab-request:update",
    "lab-report:create",
    "lab-reports:view",
    "notifications:view",
    "profile:view",
    "profile:update",
  ],
  pharmacist: [
    "pharmacy:view",
    "prescriptions:view",
    "prescription:dispense",
    "inventory:view",
    "inventory:manage",
    "notifications:view",
    "profile:view",
    "profile:update",
  ],
  receptionist: [
    "appointment:create",
    "appointment:update",
    "appointment:cancel",
    "appointment:checkin",
    "appointment:view",
    "queue:view",
    "queue:update",
    "doctor:view",
    "department:view",
    "search:view",
    "patient:create",
    "billing:view",
    "billing:manage",
    "payment:record",
    "notifications:view",
    "profile:view",
    "profile:update",
    "operations:view",
    "family-member:manage",
  ],
  administrator: [
    "appointment:create",
    "appointment:update",
    "appointment:cancel",
    "appointment:checkin",
    "appointment:view",
    "queue:view",
    "queue:update",
    "doctor:view",
    "department:view",
    "search:view",
    "user:view",
    "user:manage",
    "reports:view",
    "settings:view",
    "billing:view",
    "billing:manage",
    "payment:record",
    "inventory:view",
    "notifications:view",
    "profile:view",
    "profile:update",
    "operations:view",
    "family-member:manage",
    "medical-history:create",
    "clinical-attachment:create",
    "telemedicine:join",
  ],
};

export const landingPathByRole: Record<UserRole, string> = {
  patient: "/dashboard/patient",
  doctor: "/dashboard/doctor",
  receptionist: "/dashboard/reception",
  laboratory: "/dashboard/laboratory",
  pharmacist: "/dashboard/pharmacy",
  administrator: "/dashboard/admin",
};

export function getCapabilitiesForRole(role: UserRole) {
  return roleCapabilities[role];
}
